CREATE DATABASE IF NOT EXISTS quiz_db CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE quiz_db;

CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    answer CHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
